### ISSUE TITLE
Is this package following PvP or SemVer versioning-policy?

### ISSUE THREAD

**Issue by Drezil** [Lysxia/generic-data#15]
As the current Vension is only in stackage-nightly, but stackage-lts is stuck on version 0.3.0.0 i wonder if this package follows SemVer or PvP.

https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#lts-package-guarantees-and-exceptions

tl;dr:
In PvP x.y.z -> x.(y+1).0 is a major-release and not updated in lts, as these have always breaking changes
In SemVer x.y.z -> x.(y+1).0 is a minor-release with no breaking changes and x.y.z -> (x+1).0.0 are the major-releases. Thus the first is upgraded in stackage-lts.

Stackage defaults to PvP until the maintainer explicitly states that the package follows SemVer via issue on stackage-github.

I would like to see the current version in lts-13.xx instead of waiting for lts-14.xx (wich may be the new ghc-8.8 if we get no other ghc-8.6.5-point-release).

i see 2 ways to achieve that with the current state:
1. Create issue on stackage to be registered as SemVer
2. Do a 0.3.1.0, 0.4.1.0 & 0.5.1.0 with the current version and follow PvP after 0.6.0.0

However any decision is your call :)

**Comment by sjakobi** [comment]
@Drezil are you aware that you can use v0.6.0.0 with LTS-13 by using the `extra-deps` field? 

Your `stack.yaml` would look somewhat like this:

```
resolver: lts-13.0
extra-deps:
  - generic-data-0.6.0.0
```
---

Using a different versioning scheme than the PVP would IMHO cause a lot of headaches for most downstream users.

**Comment by Lysxia** [comment]
I'm using the PVP and most releases indeed contain breaking changes. I'm not too worried about that as it's so easy to upgrade locally, as sjakobi points out.
