### ISSUE TITLE
Should Generically's Monoid instance be based on the Semigroup instance?

### ISSUE THREAD

**Issue by yairchu** [Lysxia/generic-data#17]
When a user has a custom `Semigroup` instance, they may want to derive a `Monoid` instance that uses their custom `<>`, which may behave differently from `gmappend'`!

Do you think it would it be a good idea if

    instance (Semigroup a, Generic a, Monoid (Rep a ())) => Monoid (Generically a) where
        mempty = gmempty

So whenever someone derives both the `Semigroup` and `Monoid` instances via `Generically` all will be the same (except for less code generated due to reusing `<>`?).

But when only deriving `Monoid` via `Generically`, the derived instance would be consistent with the custom `Semigroup` instance (assuming that the `gmempty` fits the manual instance wrt the `Monoid` laws)

**Comment by Lysxia** [comment]
Sure, I like that idea!

**Comment by yairchu** [comment]
Cool :) So I'll send a PR

**Comment by Lysxia** [comment]
Great idea, thanks again! Released in `0.7.0.0`.
